"""add is_demo to clinics

Revision ID: 6ee0d5cb78ef
Revises: c86bbbc14fad
Create Date: 2026-09-20 09:51:25.863248
"""
from alembic import op
import sqlalchemy as sa


revision = '6ee0d5cb78ef'
down_revision = 'c86bbbc14fad'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
    'clinics',
    sa.Column('is_demo', sa.Boolean(), nullable=False, server_default=sa.false())
)
    op.create_index(op.f('ix_clinics_is_demo'), 'clinics', ['is_demo'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clinics_is_demo'), table_name='clinics')
    op.drop_column('clinics', 'is_demo')
    # ### end Alembic commands ###
